signup page including validation
FevenSeyfu/Learnovation-by-innov8ors pull request #12
Opened 2024-07-01 16:59 UTC by oyinmi

2024-07-01 17:55 UTC, FevenSeyfu requested changes
Hi @oyinmi ,  You have done a great job however I have noticed your branch is way behind the main branch. I suggest you update the branch with changes from main. you can use the below to rebase your branch.                       
```suggestion 
git fetch origin main
git rebase origin/main
// if there are conflicts continue to resolve and 
git add .
git rebase --continue
```
- please also include authentications methods with google using oAuth and github

2024-07-01 17:55 UTC, FevenSeyfu commented on Frontend/src/assets/images/Frame 422.png
Hi @oyinmi  please note the logo has already been added and used for the Header please,reuse that to avoid duplication

2024-07-01 17:55 UTC, FevenSeyfu commented on Frontend/src/Pages/Authentication/SignUp.jsx
> +  password: Yup.string().required('Required'),
Please include restriction to password strength such as 
- at least 8 Characters or Longer,
- include unique characters etc..

2024-07-01 17:55 UTC, FevenSeyfu commented on Frontend/src/Pages/Authentication/SignUp.jsx
> +              <TextInput
For better UX please protect password as per the design
![image](https://github.com/FevenSeyfu/Learnovation-by-innov8ors/assets/91325016/7308c05b-dba7-4f47-98bf-037ec7ee2260)

2024-07-01 17:55 UTC, FevenSeyfu commented on Frontend/src/Pages/Authentication/SignUp.jsx
> +              </div>
Please change span to a link that navigate to /login
```suggestion
 import { Link } from 'react-router-dom';
<div className="flex justify-end">
  <p className="text-sm font-semibold">
    Already have an account? <Link to="/login">Login</Link>
  </p>
</div>
```

2024-07-01 17:58 UTC, oyinmi commented on Frontend/src/assets/images/Frame 422.png
I am still working on the tasks.. i'm not through yet

2024-07-03 15:38 UTC, FevenSeyfu approved these changes
Great!

2024-07-03 15:44 UTC, merged